version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
  - package-ecosystem: "bundler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    groups:
      bundler-lint:
        patterns:
          - "rubocop"
          - "rubocop-*"
          - "slim_lint"
      bundler-dev:
        dependency-type: "development"
        update-types:
          - minor
          - patch
      bundler-all:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - rails
