version: '3'
services:
  web:
    build: .
    environment:
      - "MONGOHQ=mongodb://mongo:27017"
      - "WILLPING=true"
    restart: always
    ports:
     - "3001:3000"
    volumes:
      - ./:/usr/local/app
      - /usr/local/app/node_modules
    links:
      - mongo
  mongo:
    image: "mongo:3-jessie"
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
