alexandria:
  name: "Alexandria, VA"
  endpoint: "https://request.alexandriava.gov/GeoReport/Service.ashx/"
  # Zlib::DataError: incorrect header check when using default headers that include `deflate`
  headers: { accept_encoding: "" }
  format: 'xml'
annaberg_buchholz:
  name: 'Annaberg-Buchholz, Deutschland'
  endpoint: 'http://anliegen.annaberg-buchholz.de/georeport/v2/'
  jurisdiction: 'annberg-buchholz.de'
baltimore:
  name: 'Baltimore, MD'
  endpoint: "http://311.baltimorecity.gov/open311/v2/"
  jurisdiction: 'baltimorecity.gov'
bloomington:
  name: 'Bloomington, IN'
  endpoint: "https://bloomington.in.gov/crm/open311/v2/"
  jurisdiction: 'bloomington.in.gov'
bonn:
  name: 'Bonn, Deutschland'
  endpoint: 'https://anliegen.bonn.de/georeport/v2'
boston:
  name: 'Boston, MA'
  endpoint: "https://mayors24.cityofboston.gov/open311/v2/"
brookline:
  name: 'Brookline, MA'
  endpoint: "http://spot.brooklinema.gov/open311/v2/"
  jurisdiction: 'brooklinema.gov'
bruhl:
  name: 'Brühl, Deutschland'
  endpoint: 'https://www.achtet-auf-bruehl.de/georeport/v2/'
  jurisdiction: 'bruehl.de'
chicago:
  name: 'Chicago, IL'
  endpoint: "http://311api.cityofchicago.org/open311/v2/"
columbus:
  name: 'Columbus, IN'
  endpoint: 'http://csr.columbus.in.gov/csr/open311/v2/'
  jurisdiction: 'columbus.in.gov'
dc:
  name: 'Washington, DC'
  endpoint: "http://app.311.dc.gov/CWI/Open311/v2/"
  format: "xml"
  jurisdiction: "dc.gov"
giessen:
  name: 'Gießen, Deutschland'
  endpoint: 'https://maengelmelder.giessen.de/georeport/v2/'
grand_rapids:
  name: 'Grand Rapids, MI'
  endpoint: "http://grcity.spotreporters.com/open311/v2/"
  jurisdiction: 'grcity.us'
greenwich:
  name: 'Greenwich, Britain'
  endpoint: 'https://open311.royalgreenwich.gov.uk/'
  format: 'xml'
  notes: 'JSON endpoint returns non-standard objects'
helsinki:
  name: 'Helsinki, Suomi'
  endpoint: "https://asiointi.hel.fi/palautews/rest/v1/"
koln:
  name: 'Köln / Cologne, Deutschland'
  endpoint: 'https://sags-uns.stadt-koeln.de/georeport/v2/'
  jurisdiction: 'stadt-koeln.de'
lamia:
  name: 'Lamía, Elláda'
  endpoint: 'https://participation.citysdk.lamia-city.gr/rest/open311/v1/'
ottawa:
  name: 'Ottawa, ON'
  endpoint: 'https://city-of-ottawa-prod.apigee.net/open311/v2/'
peoria:
  name: 'Peoria, IL'
  endpoint: 'https://ureport.peoriagov.org/crm/open311/v2/'
  jurisdiction: 'peoriagov.org'
rostok:
  name: 'Rostock, Deutschland'
  endpoint: 'https://geo.sv.rostock.de/citysdk/'
  jurisdiction: 'rostock.de'
san_francisco:
  name: 'San Francisco, CA'
  endpoint: "http://mobile311.sfgov.org/open311/v2/"
  jurisdiction: 'sfgov.org'
siegburg:
  name: 'Siegburg, Deutschland'
  endpoint: 'http://anliegen.siegburg.de/georeport/v2/'
  jurisdiction: 'siegburg.de'
surrey:
  name: 'Surrey, BC'
  endpoint: 'https://cosmos.surrey.ca/api/open311/'
  jurisdiction: 'surrey.ca'
toronto:
  name: 'Toronto, ON'
  endpoint: "https://secure.toronto.ca/webwizard/ws/"
  jurisdiction: "toronto.ca"
turku:
  name: 'Turku, Suomi'
  endpoint: 'https://api.turku.fi/feedback/v1/'
